# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Rohit Datta
tagline:          'Software Engineer'
description:      'Software engineer living in San Francisco, currently at Apple'
url:              https://rohitdatta.github.io
baseurl:          /

author:
  name:           'Rohit Datta'
  url:            https://rohitdatta.com

paginate_path:    "/blog/page:num/"
paginate:         5

github:
  repo:           https://github.com/rohitdatta/hyde

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist